openapi: 3.0.3
info:
  title: Route Optimizer API
  description: |-
    API for route optimization.
    Some useful links:
    - [Repository](https://github.com/brmeloleite01/ateliware-tech-assessment)
    - [Web-App Consumer]()
  contact:
    email: brmelo.leite@gmail.com
  version: '1.0'
  
servers:
  - url: 'not defined yet'
tags:
  - name: route-optimizer
paths:
  /route-optimizer/fastest:
    post:
      tags:
        - route-optimizer
      summary: it generates fastest path
      operationId: generated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectsPosition'
          
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          description: Invalid input

  
components:
  schemas:
    Route:
      type: object
      properties:
        pathes:
          type: array
          items:
            type: array
            items:
              type: string
            example: 
              - - "A1"
                - "A2"
                - "A3"
                - "A4"
              - - "A5"
                - "A6"
                - "A7"
        time:
          type: number
          format: float
          example: 3.4
          description: Seconds
    ObjectsPosition:
      type: object
      properties:
        drone:
          type: string
          example: "A1"
        start:
          type: string
          example: "A4"
        end:
          type: string
          example: "A6"