openapi: 3.0.3
info:
  title: Searches API
  description: |-
    This API exports services to storage and list searches.
    Some useful links:
    - [Repository](https://github.com/brmeloleite01/ateliware-tech-assessment)
    - [Web-App Consumer]()
  contact:
    email: brmelo.leite@gmail.com
  version: '1.0'
  
servers:
  - url: 'not defined yet'
tags:
  - name: search
paths:
  /searches:
    post:
      tags:
        - search
      summary: Add a new search to database
      operationId: add
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Search'
          
        required: true
      responses:
        '201':
          description: Successful operation
        '400':
          description: Invalid input

    get:
      tags:
        - search
      summary: List searches by query params
      description: By default, the list is limited to 10 items and sorted in descending order.
      operationId: list
      parameters:
        - name: limit
          in: query
          description: items limit
          required: false
          schema:
            type: string
            default: 10
           
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Search'          
           
        
  
components:
  schemas:
    Search:
      type: object
      properties:
        drone:
          type: string
          example: "A1"
        start:
          type: string
          example: "A4"
        end:
          type: string
          example: "A6"
        date:
          type: string
          format: date-time
          example: "2023-06-23T23:43:14.904Z"
        result:
          type: object
          properties:
            pathes:
              type: array
              items:
                type: array
                items:
                  type: string
                example: 
                  - - "A1"
                    - "A2"
                    - "A3"
                    - "A4"
                  - - "A5"
                    - "A6"
                    - "A7"
            time:
              type: number
              format: float
              example: 3.4
              description: Seconds
      
